### ISSUE TITLE
Some appearance can be improve.

### ISSUE THREAD

**Issue by SariyaP** [KhunakornP/A-plus-management#174]
## Problems
On the title A-Levels is not the same as the choices below.
![image](https://github.com/user-attachments/assets/fcd4ef92-1dc9-4547-a472-4fbdb262ce23)
Minor capital letter mistake.
![image](https://github.com/user-attachments/assets/f3537ffe-a48e-4794-a22d-2eb91e634e1c)
There are some duplicate faculty which there are no context of why the score is not the same since it's the same faculty and criteria.
![image](https://github.com/user-attachments/assets/68be96b3-0fab-4fd7-9d2c-dd9ba8519ebe)
There is a blank space between 00 and 01 which I don't know if it's intentional.
![image](https://github.com/user-attachments/assets/70a6a04f-9175-40af-98a1-856f76bda9c8)

**Comment by KhunakornP** [comment]
I can confirm that the extra duplicate faculties are not intended. I will also be fixing the grammatical mistakes as well. As for the time wheel I will have @BioB3 look into it.

**Comment by KhunakornP** [comment]
Can you provide some information on what browser, browser version, and OS you are currently using?

**Comment by BioB3** [comment]
The blank space between 00 and 01 is browser-based since we use `datetime-local` input. The control's UI varies from browser to browser (provided below), in some browsers with no support, the input field is just a `text` input. So this is intentional.

Microsoft Edge Version 131.0.2903.63
<img src="https://github.com/user-attachments/assets/e03f6bac-ae89-465c-831c-948e6b2c5992" width="400">

Mozilla Firefox Version 132.0.2
<img src="https://github.com/user-attachments/assets/71a003b8-18bb-40f3-bd9d-f9b873a2da2c" width="400">

**Comment by Jangsoodlor** [comment]
I suspected that the duplicate faculty can be because of KU has different Engineering faculties in different campus, as we doesn't separated faculties by campus.  One potential way to fix this is just locked it to Bang Khen campus but I will discuss this with the team first.
