### ISSUE TITLE
Wiki Home page: "Retrospective" and "Summary" refer to the same page

### ISSUE THREAD

**Issue by jbrucker** [KhunakornP/A-plus-management#60]
What have two links in Home?

**Comment by KhunakornP** [comment]
During the retrospective I miss interpreted the summary link to be a summary of lessons learned during development as a whole so I added a retrospective link.
I think that summary is better since the retrospective page contains the major points of the iteration retrospective, so I've removed retrospective from the home page and I think we will create a new page for our experiences working on the project.
